name: 'Build Repo Site'
description: >
  Structurizr static site generator.
  Outputs to: `build/site`
inputs:
  repository:
    description: 'Repository name with owner. For example, actions/checkout'
    default: ${{ github.repositoryUrl }}
  workspace-file:
    description: Relative path within the Git repository of the workspace file (always required)
    required: true
  default-branch:
    description: The default branch
    required: true
  exclude-branches:
    description: Comma-separated list of branches to exclude from the generated site
  token:
    description: Personal access token (PAT) used to fetch the repository.
    default: ${{ github.token }}
runs:
  using: 'docker'
  image: 'Dockerfile.action'
  env:
    GITHUB_TOKEN: ${{ inputs.token }}
  args:
    - generate-site
    - --git-url
    - ${{ inputs.repository }}
    - --workspace-file
    - ${{ inputs.workspace-file }}
    - --all-branches
    - --exclude-branches
    - gh-pages,${{ inputs.exclude-branches }}
    - --default-branch
    - ${{ inputs.default-branch }}
